// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public/proto/message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_public_2fproto_2fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_public_2fproto_2fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_public_2fproto_2fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_public_2fproto_2fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_public_2fproto_2fmessage_2eproto;
namespace messenger {
class SecureEnvelope;
struct SecureEnvelopeDefaultTypeInternal;
extern SecureEnvelopeDefaultTypeInternal _SecureEnvelope_default_instance_;
}  // namespace messenger
PROTOBUF_NAMESPACE_OPEN
template<> ::messenger::SecureEnvelope* Arena::CreateMaybeMessage<::messenger::SecureEnvelope>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace messenger {

// ===================================================================

class SecureEnvelope final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messenger.SecureEnvelope) */ {
 public:
  inline SecureEnvelope() : SecureEnvelope(nullptr) {}
  ~SecureEnvelope() override;
  explicit PROTOBUF_CONSTEXPR SecureEnvelope(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SecureEnvelope(const SecureEnvelope& from);
  SecureEnvelope(SecureEnvelope&& from) noexcept
    : SecureEnvelope() {
    *this = ::std::move(from);
  }

  inline SecureEnvelope& operator=(const SecureEnvelope& from) {
    CopyFrom(from);
    return *this;
  }
  inline SecureEnvelope& operator=(SecureEnvelope&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SecureEnvelope& default_instance() {
    return *internal_default_instance();
  }
  static inline const SecureEnvelope* internal_default_instance() {
    return reinterpret_cast<const SecureEnvelope*>(
               &_SecureEnvelope_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SecureEnvelope& a, SecureEnvelope& b) {
    a.Swap(&b);
  }
  inline void Swap(SecureEnvelope* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SecureEnvelope* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SecureEnvelope* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SecureEnvelope>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SecureEnvelope& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SecureEnvelope& from) {
    SecureEnvelope::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SecureEnvelope* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messenger.SecureEnvelope";
  }
  protected:
  explicit SecureEnvelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNonceFieldNumber = 1,
    kCiphertextFieldNumber = 2,
    kSenderIdFieldNumber = 3,
    kRecipientIdFieldNumber = 4,
  };
  // bytes nonce = 1;
  void clear_nonce();
  const std::string& nonce() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nonce(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nonce();
  PROTOBUF_NODISCARD std::string* release_nonce();
  void set_allocated_nonce(std::string* nonce);
  private:
  const std::string& _internal_nonce() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nonce(const std::string& value);
  std::string* _internal_mutable_nonce();
  public:

  // bytes ciphertext = 2;
  void clear_ciphertext();
  const std::string& ciphertext() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ciphertext(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ciphertext();
  PROTOBUF_NODISCARD std::string* release_ciphertext();
  void set_allocated_ciphertext(std::string* ciphertext);
  private:
  const std::string& _internal_ciphertext() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ciphertext(const std::string& value);
  std::string* _internal_mutable_ciphertext();
  public:

  // string sender_id = 3;
  void clear_sender_id();
  const std::string& sender_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_id();
  PROTOBUF_NODISCARD std::string* release_sender_id();
  void set_allocated_sender_id(std::string* sender_id);
  private:
  const std::string& _internal_sender_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_id(const std::string& value);
  std::string* _internal_mutable_sender_id();
  public:

  // string recipient_id = 4;
  void clear_recipient_id();
  const std::string& recipient_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_recipient_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_recipient_id();
  PROTOBUF_NODISCARD std::string* release_recipient_id();
  void set_allocated_recipient_id(std::string* recipient_id);
  private:
  const std::string& _internal_recipient_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_recipient_id(const std::string& value);
  std::string* _internal_mutable_recipient_id();
  public:

  // @@protoc_insertion_point(class_scope:messenger.SecureEnvelope)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nonce_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ciphertext_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recipient_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_public_2fproto_2fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SecureEnvelope

// bytes nonce = 1;
inline void SecureEnvelope::clear_nonce() {
  _impl_.nonce_.ClearToEmpty();
}
inline const std::string& SecureEnvelope::nonce() const {
  // @@protoc_insertion_point(field_get:messenger.SecureEnvelope.nonce)
  return _internal_nonce();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SecureEnvelope::set_nonce(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nonce_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messenger.SecureEnvelope.nonce)
}
inline std::string* SecureEnvelope::mutable_nonce() {
  std::string* _s = _internal_mutable_nonce();
  // @@protoc_insertion_point(field_mutable:messenger.SecureEnvelope.nonce)
  return _s;
}
inline const std::string& SecureEnvelope::_internal_nonce() const {
  return _impl_.nonce_.Get();
}
inline void SecureEnvelope::_internal_set_nonce(const std::string& value) {
  
  _impl_.nonce_.Set(value, GetArenaForAllocation());
}
inline std::string* SecureEnvelope::_internal_mutable_nonce() {
  
  return _impl_.nonce_.Mutable(GetArenaForAllocation());
}
inline std::string* SecureEnvelope::release_nonce() {
  // @@protoc_insertion_point(field_release:messenger.SecureEnvelope.nonce)
  return _impl_.nonce_.Release();
}
inline void SecureEnvelope::set_allocated_nonce(std::string* nonce) {
  if (nonce != nullptr) {
    
  } else {
    
  }
  _impl_.nonce_.SetAllocated(nonce, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nonce_.IsDefault()) {
    _impl_.nonce_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messenger.SecureEnvelope.nonce)
}

// bytes ciphertext = 2;
inline void SecureEnvelope::clear_ciphertext() {
  _impl_.ciphertext_.ClearToEmpty();
}
inline const std::string& SecureEnvelope::ciphertext() const {
  // @@protoc_insertion_point(field_get:messenger.SecureEnvelope.ciphertext)
  return _internal_ciphertext();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SecureEnvelope::set_ciphertext(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ciphertext_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messenger.SecureEnvelope.ciphertext)
}
inline std::string* SecureEnvelope::mutable_ciphertext() {
  std::string* _s = _internal_mutable_ciphertext();
  // @@protoc_insertion_point(field_mutable:messenger.SecureEnvelope.ciphertext)
  return _s;
}
inline const std::string& SecureEnvelope::_internal_ciphertext() const {
  return _impl_.ciphertext_.Get();
}
inline void SecureEnvelope::_internal_set_ciphertext(const std::string& value) {
  
  _impl_.ciphertext_.Set(value, GetArenaForAllocation());
}
inline std::string* SecureEnvelope::_internal_mutable_ciphertext() {
  
  return _impl_.ciphertext_.Mutable(GetArenaForAllocation());
}
inline std::string* SecureEnvelope::release_ciphertext() {
  // @@protoc_insertion_point(field_release:messenger.SecureEnvelope.ciphertext)
  return _impl_.ciphertext_.Release();
}
inline void SecureEnvelope::set_allocated_ciphertext(std::string* ciphertext) {
  if (ciphertext != nullptr) {
    
  } else {
    
  }
  _impl_.ciphertext_.SetAllocated(ciphertext, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ciphertext_.IsDefault()) {
    _impl_.ciphertext_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messenger.SecureEnvelope.ciphertext)
}

// string sender_id = 3;
inline void SecureEnvelope::clear_sender_id() {
  _impl_.sender_id_.ClearToEmpty();
}
inline const std::string& SecureEnvelope::sender_id() const {
  // @@protoc_insertion_point(field_get:messenger.SecureEnvelope.sender_id)
  return _internal_sender_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SecureEnvelope::set_sender_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messenger.SecureEnvelope.sender_id)
}
inline std::string* SecureEnvelope::mutable_sender_id() {
  std::string* _s = _internal_mutable_sender_id();
  // @@protoc_insertion_point(field_mutable:messenger.SecureEnvelope.sender_id)
  return _s;
}
inline const std::string& SecureEnvelope::_internal_sender_id() const {
  return _impl_.sender_id_.Get();
}
inline void SecureEnvelope::_internal_set_sender_id(const std::string& value) {
  
  _impl_.sender_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SecureEnvelope::_internal_mutable_sender_id() {
  
  return _impl_.sender_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SecureEnvelope::release_sender_id() {
  // @@protoc_insertion_point(field_release:messenger.SecureEnvelope.sender_id)
  return _impl_.sender_id_.Release();
}
inline void SecureEnvelope::set_allocated_sender_id(std::string* sender_id) {
  if (sender_id != nullptr) {
    
  } else {
    
  }
  _impl_.sender_id_.SetAllocated(sender_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_id_.IsDefault()) {
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messenger.SecureEnvelope.sender_id)
}

// string recipient_id = 4;
inline void SecureEnvelope::clear_recipient_id() {
  _impl_.recipient_id_.ClearToEmpty();
}
inline const std::string& SecureEnvelope::recipient_id() const {
  // @@protoc_insertion_point(field_get:messenger.SecureEnvelope.recipient_id)
  return _internal_recipient_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SecureEnvelope::set_recipient_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.recipient_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messenger.SecureEnvelope.recipient_id)
}
inline std::string* SecureEnvelope::mutable_recipient_id() {
  std::string* _s = _internal_mutable_recipient_id();
  // @@protoc_insertion_point(field_mutable:messenger.SecureEnvelope.recipient_id)
  return _s;
}
inline const std::string& SecureEnvelope::_internal_recipient_id() const {
  return _impl_.recipient_id_.Get();
}
inline void SecureEnvelope::_internal_set_recipient_id(const std::string& value) {
  
  _impl_.recipient_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SecureEnvelope::_internal_mutable_recipient_id() {
  
  return _impl_.recipient_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SecureEnvelope::release_recipient_id() {
  // @@protoc_insertion_point(field_release:messenger.SecureEnvelope.recipient_id)
  return _impl_.recipient_id_.Release();
}
inline void SecureEnvelope::set_allocated_recipient_id(std::string* recipient_id) {
  if (recipient_id != nullptr) {
    
  } else {
    
  }
  _impl_.recipient_id_.SetAllocated(recipient_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.recipient_id_.IsDefault()) {
    _impl_.recipient_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messenger.SecureEnvelope.recipient_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messenger

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_public_2fproto_2fmessage_2eproto
