// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public/proto/message.proto

#include "public/proto/message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace messenger {
PROTOBUF_CONSTEXPR SecureEnvelope::SecureEnvelope(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nonce_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ciphertext_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sender_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.recipient_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SecureEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SecureEnvelopeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SecureEnvelopeDefaultTypeInternal() {}
  union {
    SecureEnvelope _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SecureEnvelopeDefaultTypeInternal _SecureEnvelope_default_instance_;
}  // namespace messenger
static ::_pb::Metadata file_level_metadata_public_2fproto_2fmessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_public_2fproto_2fmessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_public_2fproto_2fmessage_2eproto = nullptr;

const uint32_t TableStruct_public_2fproto_2fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messenger::SecureEnvelope, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messenger::SecureEnvelope, _impl_.nonce_),
  PROTOBUF_FIELD_OFFSET(::messenger::SecureEnvelope, _impl_.ciphertext_),
  PROTOBUF_FIELD_OFFSET(::messenger::SecureEnvelope, _impl_.sender_id_),
  PROTOBUF_FIELD_OFFSET(::messenger::SecureEnvelope, _impl_.recipient_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::messenger::SecureEnvelope)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::messenger::_SecureEnvelope_default_instance_._instance,
};

const char descriptor_table_protodef_public_2fproto_2fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032public/proto/message.proto\022\tmessenger\""
  "\\\n\016SecureEnvelope\022\r\n\005nonce\030\001 \001(\014\022\022\n\nciph"
  "ertext\030\002 \001(\014\022\021\n\tsender_id\030\003 \001(\t\022\024\n\014recip"
  "ient_id\030\004 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_public_2fproto_2fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_public_2fproto_2fmessage_2eproto = {
    false, false, 141, descriptor_table_protodef_public_2fproto_2fmessage_2eproto,
    "public/proto/message.proto",
    &descriptor_table_public_2fproto_2fmessage_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_public_2fproto_2fmessage_2eproto::offsets,
    file_level_metadata_public_2fproto_2fmessage_2eproto, file_level_enum_descriptors_public_2fproto_2fmessage_2eproto,
    file_level_service_descriptors_public_2fproto_2fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_public_2fproto_2fmessage_2eproto_getter() {
  return &descriptor_table_public_2fproto_2fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_public_2fproto_2fmessage_2eproto(&descriptor_table_public_2fproto_2fmessage_2eproto);
namespace messenger {

// ===================================================================

class SecureEnvelope::_Internal {
 public:
};

SecureEnvelope::SecureEnvelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messenger.SecureEnvelope)
}
SecureEnvelope::SecureEnvelope(const SecureEnvelope& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SecureEnvelope* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nonce_){}
    , decltype(_impl_.ciphertext_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.recipient_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.nonce_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nonce_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nonce().empty()) {
    _this->_impl_.nonce_.Set(from._internal_nonce(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ciphertext_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ciphertext_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ciphertext().empty()) {
    _this->_impl_.ciphertext_.Set(from._internal_ciphertext(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sender_id().empty()) {
    _this->_impl_.sender_id_.Set(from._internal_sender_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.recipient_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recipient_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_recipient_id().empty()) {
    _this->_impl_.recipient_id_.Set(from._internal_recipient_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:messenger.SecureEnvelope)
}

inline void SecureEnvelope::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nonce_){}
    , decltype(_impl_.ciphertext_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.recipient_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.nonce_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nonce_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ciphertext_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ciphertext_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.recipient_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recipient_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SecureEnvelope::~SecureEnvelope() {
  // @@protoc_insertion_point(destructor:messenger.SecureEnvelope)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SecureEnvelope::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nonce_.Destroy();
  _impl_.ciphertext_.Destroy();
  _impl_.sender_id_.Destroy();
  _impl_.recipient_id_.Destroy();
}

void SecureEnvelope::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SecureEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:messenger.SecureEnvelope)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nonce_.ClearToEmpty();
  _impl_.ciphertext_.ClearToEmpty();
  _impl_.sender_id_.ClearToEmpty();
  _impl_.recipient_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SecureEnvelope::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes nonce = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_nonce();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes ciphertext = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_ciphertext();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string sender_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_sender_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "messenger.SecureEnvelope.sender_id"));
        } else
          goto handle_unusual;
        continue;
      // string recipient_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_recipient_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "messenger.SecureEnvelope.recipient_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SecureEnvelope::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messenger.SecureEnvelope)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes nonce = 1;
  if (!this->_internal_nonce().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_nonce(), target);
  }

  // bytes ciphertext = 2;
  if (!this->_internal_ciphertext().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_ciphertext(), target);
  }

  // string sender_id = 3;
  if (!this->_internal_sender_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sender_id().data(), static_cast<int>(this->_internal_sender_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messenger.SecureEnvelope.sender_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_sender_id(), target);
  }

  // string recipient_id = 4;
  if (!this->_internal_recipient_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_recipient_id().data(), static_cast<int>(this->_internal_recipient_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messenger.SecureEnvelope.recipient_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_recipient_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messenger.SecureEnvelope)
  return target;
}

size_t SecureEnvelope::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messenger.SecureEnvelope)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes nonce = 1;
  if (!this->_internal_nonce().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_nonce());
  }

  // bytes ciphertext = 2;
  if (!this->_internal_ciphertext().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_ciphertext());
  }

  // string sender_id = 3;
  if (!this->_internal_sender_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sender_id());
  }

  // string recipient_id = 4;
  if (!this->_internal_recipient_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_recipient_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SecureEnvelope::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SecureEnvelope::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SecureEnvelope::GetClassData() const { return &_class_data_; }


void SecureEnvelope::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SecureEnvelope*>(&to_msg);
  auto& from = static_cast<const SecureEnvelope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messenger.SecureEnvelope)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nonce().empty()) {
    _this->_internal_set_nonce(from._internal_nonce());
  }
  if (!from._internal_ciphertext().empty()) {
    _this->_internal_set_ciphertext(from._internal_ciphertext());
  }
  if (!from._internal_sender_id().empty()) {
    _this->_internal_set_sender_id(from._internal_sender_id());
  }
  if (!from._internal_recipient_id().empty()) {
    _this->_internal_set_recipient_id(from._internal_recipient_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SecureEnvelope::CopyFrom(const SecureEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messenger.SecureEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SecureEnvelope::IsInitialized() const {
  return true;
}

void SecureEnvelope::InternalSwap(SecureEnvelope* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nonce_, lhs_arena,
      &other->_impl_.nonce_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ciphertext_, lhs_arena,
      &other->_impl_.ciphertext_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sender_id_, lhs_arena,
      &other->_impl_.sender_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.recipient_id_, lhs_arena,
      &other->_impl_.recipient_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SecureEnvelope::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_public_2fproto_2fmessage_2eproto_getter, &descriptor_table_public_2fproto_2fmessage_2eproto_once,
      file_level_metadata_public_2fproto_2fmessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace messenger
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::messenger::SecureEnvelope*
Arena::CreateMaybeMessage< ::messenger::SecureEnvelope >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messenger::SecureEnvelope >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
